* Massive and Accurate Coronavirus Diagnosing via Machine Learning

Humankind is facing an unprecedented disaster. I believe that we, as
IT professionals, should act to help curb the pandemic. Below is a
project idea. I invite anyone with the needed capabilities and
resources to try it out.

First, we design a web platform, a website or an app, to allow people
to update their symptoms continuously. Global Initiatives such as
https://coronastatus.us and https://coronastatus.fr enable people to
report their health condition related to the virus anonymously. Such
websites are useful for the government to predict the corona spread,
but for diagnosing, we probably need refined information. Any info
that would help a physician is helpful, e.g., "day 1 – I got a sore
throat; day 2 – I got a dry cough; day 3 – My body temperatures is 38
degrees." The web platform should also allow people to input CT scans,
blood tests, or coughing sounds, etc.

Then, we learn from the data via artificial intelligence, e.g., by
building neural networks. The learned model allows us to make a
diagnose. People will be motivated to use such a platform if they can
be provided a free diagnosis that complement doctors' decisions. I
expect that the diagnosis can be highly accurate once a large amount
of data has been collected. As an example, AI models already detect
cardiovascular disease with a success rate of 98.5%, outperforming
cardiologists.

Related to this project, Hospital Israelita Albert Einstein in Brazil
applied AI to diagnose COVID-19 cases based on data from 235
patients. Most likely, their results can be improved with data
collected from the web platform data, and in fact, hospital-provided
and web data should merge for synergies. EPFL researchers have
developed an AI-based corona diagnosing that can listen to coughing
and indicate whether the patient has COVID-19. The app has an accuracy
rate of 70%. Perhaps, the accuracy can be enhanced with the data we
would ask users to submit to the web platform.

